version: '2'
services:
  application:
    container_name: "dcscpp"
    build: .
    ports:
     - "80:3000"
  database:
    image: "mongo"
    container_name: "mongodb"
    ports:
     - "27017:27017"
